# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ee8a9b56b84cf8d9be10eb4441941003edd0150abea2a54678d014ac5991dfa964011b00709273fa9309c3972479a1f1c1352fe6ca9989ed346369cad12af4d

test:
  secret_key_base: 84f03d4e5385392e610141d111f6176ee5095544455774d0678727ff4aaa14262343ed67abedef311a78bed8e0f0212b3c31363e7c6d995ff1d6fbd0be866ff4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
